In [1]:
import numpy as np
np.__version__

'1.20.3'

In [5]:
def aryInfo(ary) :
    print('type - ' , type(ary))
    print('shape - ' , ary.shape)
    print('dimension - ' , ary.ndim)
    print('dtype - ' , ary.dtype)
    print()
    print('data - \n' , ary)

In [3]:
oneAry = np.array([0,1,2,3,4,5,6,7,8,9])
aryInfo(oneAry)

type -  <class 'numpy.ndarray'>
shape -  (10,)
dimension -  1
dtype -  int64

data - 
 [0 1 2 3 4 5 6 7 8 9]


In [4]:
data = [0,1,2,3,4,5,6,7,8,9]
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
result = []

for d in data :
    result.append(d * 2)

print(result)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [6]:
result2 = [d * 2 for d in data]
print(result2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [7]:
result3 = oneAry * 2
print(result3)

[ 0  2  4  6  8 10 12 14 16 18]


In [6]:
data01 = [1, 2, 3, 4, 5]
data02 = [10, 20, 30, 40, 50]

print(type(data01) , type(data02))

<class 'list'> <class 'list'>


In [7]:
xAry = np.array(data01)
yAry = np.array(data02)

print(type(xAry) , type(yAry))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [8]:
print('산술연산 - ')

aryInfo(xAry + yAry)

print()
aryInfo(2 * xAry + yAry)

산술연산 - 
type -  <class 'numpy.ndarray'>
shape -  (5,)
dimension -  1
dtype -  int64

data - 
 [11 22 33 44 55]

type -  <class 'numpy.ndarray'>
shape -  (5,)
dimension -  1
dtype -  int64

data - 
 [12 24 36 48 60]


In [9]:
print('비교 연산 - boolean masking')

print( xAry == 2 )
print()
aryInfo(xAry == 2 )

비교 연산 - boolean masking
[False  True False False False]

type -  <class 'numpy.ndarray'>
shape -  (5,)
dimension -  1
dtype -  bool

data - 
 [False  True False False False]


In [10]:
print('비교 연산 - boolean masking')

print( yAry > 10 )
print()
aryInfo( yAry > 10 )

비교 연산 - boolean masking
[False  True  True  True  True]

type -  <class 'numpy.ndarray'>
shape -  (5,)
dimension -  1
dtype -  bool

data - 
 [False  True  True  True  True]


In [12]:
print('논리 연산 - ')
print( (xAry == 2) | (yAry > 10) )
print()
aryInfo( (xAry == 2) | (yAry > 10) )

논리 연산 - 
[False  True  True  True  True]

type -  <class 'numpy.ndarray'>
shape -  (5,)
dimension -  1
dtype -  bool

data - 
 [False  True  True  True  True]


In [11]:
print('2개의 행과 3개의 열을 갖는 배열을 만든다면 ? - ')
twoAry = np.array([[1,2,3],[4,5,6]] , dtype = np.float64)


print()
aryInfo(twoAry)

print()
print('len() - ')
print('len() 행의 갯수 - ' ,  len(twoAry))
print('len() 행의 요소의 갯수, 즉 열을 의미한다 -  ' , len(twoAry[0]))
print('len() 행의 요소의 갯수, 즉 열을 의미한다 -  ' , len(twoAry[1]))

2개의 행과 3개의 열을 갖는 배열을 만든다면 ? - 

type -  <class 'numpy.ndarray'>
shape -  (2, 3)
dimension -  2
dtype -  float64

data - 
 [[1. 2. 3.]
 [4. 5. 6.]]

len() - 
len() 행의 갯수 -  2
len() 행의 요소의 갯수, 즉 열을 의미한다 -   3
len() 행의 요소의 갯수, 즉 열을 의미한다 -   3


In [12]:
print('3차원 - 3 * 4 2개의 레이어 - ')
threeAry = np.array([ [ [1,2,3,4], [5,6,7,8], [9,10,11,12] ], [ [13,14,15,16], [17,18,19,20], [21,22,23,24] ]])
print()
aryInfo(threeAry)

print()
print('len() - depth' , len(threeAry))
print('len() - ' , len(threeAry[0]))
print('len() - ' , len(threeAry[1]))
print('row col - ' , len(threeAry[0][0] ))

3차원 - 3 * 4 2개의 레이어 - 

type -  <class 'numpy.ndarray'>
shape -  (2, 3, 4)
dimension -  3
dtype -  int64

data - 
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

len() - depth 2
len() -  3
len() -  3
row col -  4


In [13]:
typeChange = threeAry.astype(np.float64)
aryInfo(typeChange)

type -  <class 'numpy.ndarray'>
shape -  (2, 3, 4)
dimension -  3
dtype -  float64

data - 
 [[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]]


In [14]:
idxAry = np.array([1,2,3,4,5,6,7,8,9])
aryInfo(idxAry)

type -  <class 'numpy.ndarray'>
shape -  (9,)
dimension -  1
dtype -  int64

data - 
 [1 2 3 4 5 6 7 8 9]


In [15]:
print('indexing - ')
print(idxAry[0])
print(idxAry[1])

indexing - 
1
2


In [20]:
aryInfo(twoAry)

print()
print('첫번째 행의 첫번째 열의 값 - ')
print(twoAry[0 , 0])
print()
print('마지막 행의 마지막 열 - ')
print(twoAry[-1, -1])

print()
print('첫번째 행의 전체 - ')
print(twoAry[0, : ])

print()
print('첫번째 행의 두번째부터 끝까지 - ')
print(twoAry[0 , 1 : ])


print()
print('행이 아닌 y 축의 값을 구할 때 - ')
print(twoAry[ : , 1])

type -  <class 'numpy.ndarray'>
shape -  (2, 3)
dimension -  2
dtype -  float64

data - 
 [[1. 2. 3.]
 [4. 5. 6.]]

첫번째 행의 첫번째 열의 값 - 
1.0

마지막 행의 마지막 열 - 
6.0

첫번째 행의 전체 - 
[1. 2. 3.]

첫번째 행의 두번째부터 끝까지 - 
[2. 3.]

행이 아닌 y 축의 값을 구할 때 - 
[2. 5.]


In [21]:
matrixAry = np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]])
aryInfo(matrixAry)

type -  <class 'numpy.ndarray'>
shape -  (3, 5)
dimension -  2
dtype -  int64

data - 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [25]:
print('이 행렬에서 값 7 을 인덱싱한다. - ' , matrixAry[ 1 , 2 ])
print('이 행렬에서 값 14 을 인덱싱한다. - ', matrixAry[ -1 , -1 ])
print('이 행렬에서 배열 [6, 7] 을 슬라이싱한다. - ' , matrixAry[ 1 , 1:3 ] , type(matrixAry[ 1 , 1:3 ]))
print('이 행렬에서 배열 [7, 12] 을 슬라이싱한다. - ', matrixAry[ 1:3 , 2 ])
print('이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다. - ' ,   matrixAry[ 0:2 , 3:5 ] ,
                                                                  type(matrixAry[ 0:2 , 3:5 ]) ,
                                                                  matrixAry[ 0:2 , 3:5 ].ndim)

이 행렬에서 값 7 을 인덱싱한다. -  7
이 행렬에서 값 14 을 인덱싱한다. -  14
이 행렬에서 배열 [6, 7] 을 슬라이싱한다. -  [6 7] <class 'numpy.ndarray'>
이 행렬에서 배열 [7, 12] 을 슬라이싱한다. -  [ 7 12]
이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다. -  [[3 4]
 [8 9]] <class 'numpy.ndarray'> 2


In [26]:
ary = np.array([0,1,2,3,4,5,6,7,8,9])
aryInfo(ary)

type -  <class 'numpy.ndarray'>
shape -  (10,)
dimension -  1
dtype -  int64

data - 
 [0 1 2 3 4 5 6 7 8 9]
