In [1]:
import numpy  as np
import pandas as pd

import warnings
warnings.filterwarnings(action='ignore')

from datetime import date, datetime, timedelta
from dateutil.parser import parse

import json
import urllib


print('numpy  version - ' , np.__version__)
print('pandas version - ' , pd.__version__)

numpy  version -  1.20.3
pandas version -  1.3.4


In [2]:
print('list 이용한 생성 - ')
print()

prices = pd.Series(['4000', 3000, 3500, 2000])
print(prices)

print()
print('type - ' , type(prices))

print()
print('index , values - ')
print('index  - ' , prices.index)
print('value  - ' , prices.values , type(prices.values))
prices = prices.astype('int32')
print('dtype  - ' , prices.dtype)

print()
print('원하는 값을 찾는다면? - 인덱싱이 가능하다 ')
print('마이너스 인덱싱은 불가하다')
print()
print('indexing - '   , prices[0] )
print('slicing  - \n' , prices[ : 3 ])
# print('indexing - '   , prices[-1]) -- error

list 이용한 생성 - 

0    4000
1    3000
2    3500
3    2000
dtype: object

type -  <class 'pandas.core.series.Series'>

index , values - 
index  -  RangeIndex(start=0, stop=4, step=1)
value  -  ['4000' 3000 3500 2000] <class 'numpy.ndarray'>
dtype  -  int32

원하는 값을 찾는다면? - 인덱싱이 가능하다 
마이너스 인덱싱은 불가하다

indexing -  4000
slicing  - 
 0    4000
1    3000
2    3500
dtype: int32


In [3]:
print('사용자 정의 인덱스 부여가 가능하다 - ')

prices = pd.Series([4000, 3000, 3500, 2000] ,
                    index = ['a', 'b', 'c', 'd']   )

사용자 정의 인덱스 부여가 가능하다 - 


In [4]:
print(prices)
print()
print(prices[0] , type(prices[0]) , prices['a'] )


print()
print(prices['a' : 'c'] , type(prices['a' : 'c']))
print()
print('인덱스가 존재하는지 - ' , 'a' in prices , 0 in prices)

print(prices.index)

print()
print('인덱스를 활용한 데이터 변경 - ')
prices['a'] = 10000
print()
print( prices )

a    4000
b    3000
c    3500
d    2000
dtype: int64

4000 <class 'numpy.int64'> 4000

a    4000
b    3000
c    3500
dtype: int64 <class 'pandas.core.series.Series'>

인덱스가 존재하는지 -  True False
Index(['a', 'b', 'c', 'd'], dtype='object')

인덱스를 활용한 데이터 변경 - 

a    10000
b     3000
c     3500
d     2000
dtype: int64


In [5]:
print()
print('데이터 추가 가능 - ')
prices['e'] = 6000
print( prices )
print()
print('데이터 삭제 - ')
del prices['e']
print( prices )


데이터 추가 가능 - 
a    10000
b     3000
c     3500
d     2000
e     6000
dtype: int64

데이터 삭제 - 
a    10000
b     3000
c     3500
d     2000
dtype: int64


In [6]:
prices = pd.Series([4000, 3000, 3500, 2000])
print()
print('벡터화 연산이 가능하다 - ')
print( prices * 10 )
print( prices )


벡터화 연산이 가능하다 - 
0    40000
1    30000
2    35000
3    20000
dtype: int64
0    4000
1    3000
2    3500
3    2000
dtype: int64


In [7]:
print()
print('조건식을 활용 할 수 있다 - ')

prices[ prices > 3000 ]


조건식을 활용 할 수 있다 - 


0    4000
2    3500
dtype: int64

In [8]:
print('dict , tuple , set  생성이 가능 -')
print()
person = pd.Series({ 'name' : 'Jason' , 'age' : 25 })
print( person )
print('index - ' , person.index)
print('value - ' , person.values)
print()
print()
ages = pd.Series( (10, 20, 30) )
print( ages )
print('index - ' , ages.index)
print('value - ' , ages.values)

print()
print('set 은 주의하셔야 한다 - ')
ages = pd.Series( list( {10, 20, 30} ) )
print( ages )
print('index - ' , ages.index)
print('value - ' , ages.values)

dict , tuple , set  생성이 가능 -

name    Jason
age        25
dtype: object
index -  Index(['name', 'age'], dtype='object')
value -  ['Jason' 25]


0    10
1    20
2    30
dtype: int64
index -  RangeIndex(start=0, stop=3, step=1)
value -  [10 20 30]

set 은 주의하셔야 한다 - 
0    10
1    20
2    30
dtype: int64
index -  RangeIndex(start=0, stop=3, step=1)
value -  [10 20 30]


In [9]:
tmp = pd.Series([1,2,3,4,5],
                index = ['강남', '서초', '방배', '동작', '광진'] )

tmp.name = '특정한 의미를 부여할 수 있다'
tmp.index.name= '구 구별'
tmp

구 구별
강남    1
서초    2
방배    3
동작    4
광진    5
Name: 특정한 의미를 부여할 수 있다, dtype: int64

In [10]:
tmp = pd.Series( range(10, 21) , dtype = 'f')
tmp

0     10.0
1     11.0
2     12.0
3     13.0
4     14.0
5     15.0
6     16.0
7     17.0
8     18.0
9     19.0
10    20.0
dtype: float32

In [11]:
print( tmp * 10)

0     100.0
1     110.0
2     120.0
3     130.0
4     140.0
5     150.0
6     160.0
7     170.0
8     180.0
9     190.0
10    200.0
dtype: float32


In [12]:
print( tmp[ tmp%2 == 0 ] )

0     10.0
2     12.0
4     14.0
6     16.0
8     18.0
10    20.0
dtype: float32


In [13]:
print('날짜와 시간을 인덱스로 활용한다면? - ')

day = datetime(2022, 3, 25)
print( day + timedelta(days=1) )

날짜와 시간을 인덱스로 활용한다면? - 
2022-03-26 00:00:00


In [14]:
print('[실습] 평균이 50이고 편차 5인 정규분포 데이터를 10일간 만들고 싶다면? - ')
print(' np.random.normal(50, 5, 10) ')

[실습] 평균이 50이고 편차 5인 정규분포 데이터를 10일간 만들고 싶다면? - 
 np.random.normal(50, 5, 10) 


In [15]:
np.random.normal(50, 5, 10)

array([51.33000214, 42.5967977 , 49.50260244, 49.82688661, 50.55919635,
       53.87158451, 53.08334299, 48.36381287, 59.53415891, 41.95872587])

In [16]:
factory01 = pd.Series( np.random.normal(50, 5, 10) ,
                       index = [ day + timedelta(days = d) for d in range(10) ])
factory02 = pd.Series( np.random.normal(50, 5, 10) ,
                       index = [ day + timedelta(days = d) for d in range(10) ])

In [17]:
factory01

2022-03-25    50.701058
2022-03-26    46.174267
2022-03-27    47.317256
2022-03-28    46.005921
2022-03-29    55.083138
2022-03-30    48.337512
2022-03-31    49.813267
2022-04-01    51.062722
2022-04-02    52.942698
2022-04-03    42.758621
dtype: float64

In [18]:
factory02

2022-03-25    46.370671
2022-03-26    40.500943
2022-03-27    48.480478
2022-03-28    52.356403
2022-03-29    58.505241
2022-03-30    53.336545
2022-03-31    46.792928
2022-04-01    50.435645
2022-04-02    42.711470
2022-04-03    59.807915
dtype: float64

In [19]:
factory = factory01 + factory02

In [20]:
factory

2022-03-25     97.071729
2022-03-26     86.675210
2022-03-27     95.797734
2022-03-28     98.362325
2022-03-29    113.588379
2022-03-30    101.674057
2022-03-31     96.606195
2022-04-01    101.498367
2022-04-02     95.654168
2022-04-03    102.566536
dtype: float64

In [21]:
print('결측값 확인 함수 - pd.isnull() ')
print( pd.isnull(factory) )
# print( factory.isnull() )

print()
print( factory[ factory.isnull()  ] )

print()
print( factory[ factory.notnull()  ] )

print('결측값을 넣어줄 때 - np.NaN ')
factory['2022-04-03'] = np.NaN

결측값 확인 함수 - pd.isnull() 
2022-03-25    False
2022-03-26    False
2022-03-27    False
2022-03-28    False
2022-03-29    False
2022-03-30    False
2022-03-31    False
2022-04-01    False
2022-04-02    False
2022-04-03    False
dtype: bool

Series([], dtype: float64)

2022-03-25     97.071729
2022-03-26     86.675210
2022-03-27     95.797734
2022-03-28     98.362325
2022-03-29    113.588379
2022-03-30    101.674057
2022-03-31     96.606195
2022-04-01    101.498367
2022-04-02     95.654168
2022-04-03    102.566536
dtype: float64
결측값을 넣어줄 때 - np.NaN 


In [22]:
f = factory.astype('float')
f

2022-03-25     97.071729
2022-03-26     86.675210
2022-03-27     95.797734
2022-03-28     98.362325
2022-03-29    113.588379
2022-03-30    101.674057
2022-03-31     96.606195
2022-04-01    101.498367
2022-04-02     95.654168
2022-04-03           NaN
dtype: float64

In [23]:
def frmInfo(df) :
    display('data - ' , df )
    print()
    print('shape   - ' , df.shape , df.shape[0] , df.shape[1])
    print('size    - ' , df.size )
    print('ndim    - ' , df.ndim)
    print('index   - ' , df.index    , type(df.index))
    print('columns - ' , df.columns  , type( df.columns ))
    print('values  - \n' , df.values , type(df.values) )

In [24]:
print('dict를 이용한 생성 - ' )

dict_data = {
    'col01' : [1, 2, 3],
    'col02' : [4, 5, 6],
    'col03' : [7, 8, 9],
    'col04' : [10, 11, 12],
    'col05' : [13, 14, 15]
}
tmp_df = pd.DataFrame(dict_data)
frmInfo( tmp_df )

dict를 이용한 생성 - 


'data - '

col01  col02  col03  col04  col05
0      1      4      7     10     13
1      2      5      8     11     14
2      3      6      9     12     15


shape   -  (3, 5) 3 5
size    -  15
ndim    -  2
index   -  RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns -  Index(['col01', 'col02', 'col03', 'col04', 'col05'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[ 1  4  7 10 13]
 [ 2  5  8 11 14]
 [ 3  6  9 12 15]] <class 'numpy.ndarray'>


In [25]:
print( tmp_df['col01'] , type(tmp_df['col01']) )
print( tmp_df['col01'].index , tmp_df['col01'].values)
print( tmp_df['col01'][0] , type(tmp_df['col01'][0]) )


0    1
1    2
2    3
Name: col01, dtype: int64 <class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=3, step=1) [1 2 3]
1 <class 'numpy.int64'>


In [26]:
print('리스트를 이용한 생성 - ')
print()
tmp_df = pd.DataFrame( [ [20, 'M', False] , [30, 'F', True] ] ,
                       index   = ['Name' , 'Jason'] ,
                       columns = ['나이' , '성별' , '결혼여부'])
frmInfo(tmp_df)

리스트를 이용한 생성 - 



'data - '

나이 성별   결혼여부
Name   20  M  False
Jason  30  F   True


shape   -  (2, 3) 2 3
size    -  6
ndim    -  2
index   -  Index(['Name', 'Jason'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['나이', '성별', '결혼여부'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[20 'M' False]
 [30 'F' True]] <class 'numpy.ndarray'>


In [27]:
print('인덱스 이름 변경 - rename() , inplace - ')

tmp_df.rename(columns = {'나이' : '연세' , '성별' : '남녀' , '결혼여부' : '혼인'} , inplace = True  )
tmp_df.rename(index   = {'섭섭해' : '이이슬' , '임섭순' : '이현호'} , inplace = True  )
frmInfo(tmp_df)

인덱스 이름 변경 - rename() , inplace - 


'data - '

연세 남녀     혼인
Name   20  M  False
Jason  30  F   True


shape   -  (2, 3) 2 3
size    -  6
ndim    -  2
index   -  Index(['Name', 'Jason'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['연세', '남녀', '혼인'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[20 'M' False]
 [30 'F' True]] <class 'numpy.ndarray'>


In [30]:
data = {
    '2022'   : [35325412 , 23535634 , 13453264  ,34242345] ,
    '2017'   : [100000, 200000 ,300000 , 400000 ] ,
    '2012'   : [1,2,3,4] ,
    '2010'   : [1,2,3,4] ,
    '지역'   : ['특별시' , '경상권' , '수도권' , '수도권'],
    '증가율' : [0.2324, 0.0434, 0.0944, 0.0034]
}
col_idx  = ['지역' , '2010' , '2012' , '2017' , '2022' , '증가율']
row_idx  = ['서울' , '부산' , '경기' , '인천']

tmp_frm = pd.DataFrame(data ,
                       columns = col_idx ,
                       index   = row_idx )

frmInfo( tmp_frm )

'data - '

지역  2010  2012    2017      2022     증가율
서울  특별시     1     1  100000  35325412  0.2324
부산  경상권     2     2  200000  23535634  0.0434
경기  수도권     3     3  300000  13453264  0.0944
인천  수도권     4     4  400000  34242345  0.0034


shape   -  (4, 6) 4 6
size    -  24
ndim    -  2
index   -  Index(['서울', '부산', '경기', '인천'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['지역', '2010', '2012', '2017', '2022', '증가율'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [['특별시' 1 1 100000 35325412 0.2324]
 ['경상권' 2 2 200000 23535634 0.0434]
 ['수도권' 3 3 300000 13453264 0.0944]
 ['수도권' 4 4 400000 34242345 0.0034]] <class 'numpy.ndarray'>


In [31]:
tmp_frm.index.name   = 'city'
tmp_frm.columns.name = 'feature'
tmp_frm

feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324
부산       경상권     2     2  200000  23535634  0.0434
경기       수도권     3     3  300000  13453264  0.0944
인천       수도권     4     4  400000  34242345  0.0034

In [32]:
print('index name   - ' , tmp_frm.index   , tmp_frm.index.name)
print('columns name - ' , tmp_frm.columns , tmp_frm.columns.name)

index name   -  Index(['서울', '부산', '경기', '인천'], dtype='object', name='city') city
columns name -  Index(['지역', '2010', '2012', '2017', '2022', '증가율'], dtype='object', name='feature') feature


In [33]:
print('추가 - ')
print()
tmp_frm['2017-2022 증가율'] =  ( (tmp_frm['2022'] - tmp_frm['2017']) / tmp_frm['2017'] * 100 ).round(2)
tmp_frm

추가 - 



feature   지역  2010  2012    2017      2022     증가율  2017-2022 증가율
city                                                             
서울       특별시     1     1  100000  35325412  0.2324       35225.41
부산       경상권     2     2  200000  23535634  0.0434       11667.82
경기       수도권     3     3  300000  13453264  0.0944        4384.42
인천       수도권     4     4  400000  34242345  0.0034        8460.59

In [34]:
print('삭제 - ')
del tmp_frm['2017-2022 증가율']
tmp_frm

삭제 - 


feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324
부산       경상권     2     2  200000  23535634  0.0434
경기       수도권     3     3  300000  13453264  0.0944
인천       수도권     4     4  400000  34242345  0.0034

In [35]:
tmp_subset = tmp_frm[ ['지역' , '증가율'] ]
frmInfo(tmp_subset)

'data - '

feature   지역     증가율
city                
서울       특별시  0.2324
부산       경상권  0.0434
경기       수도권  0.0944
인천       수도권  0.0034


shape   -  (4, 2) 4 2
size    -  8
ndim    -  2
index   -  Index(['서울', '부산', '경기', '인천'], dtype='object', name='city') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['지역', '증가율'], dtype='object', name='feature') <class 'pandas.core.indexes.base.Index'>
values  - 
 [['특별시' 0.2324]
 ['경상권' 0.0434]
 ['수도권' 0.0944]
 ['수도권' 0.0034]] <class 'numpy.ndarray'>


In [36]:
print('라벨 인덱싱 - ')
display( tmp_frm[ : '서울'] )

라벨 인덱싱 - 


feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324

In [37]:
print()
print('배열 인덱싱 - ')
display( tmp_frm[ : 1] )


배열 인덱싱 - 


feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324

In [38]:
tmp_frm

feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324
부산       경상권     2     2  200000  23535634  0.0434
경기       수도권     3     3  300000  13453264  0.0944
인천       수도권     4     4  400000  34242345  0.0034

In [40]:
print('행 인덱싱으로 서울 - 경기까지 필터링한다면? - ')

print('라벨 인덱싱 - ')
display( tmp_frm[ '서울' : '경기'] )

print()
print('배열 인덱싱 - ')
display( tmp_frm[ 0 : 3] )

행 인덱싱으로 서울 - 경기까지 필터링한다면? - 
라벨 인덱싱 - 


feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324
부산       경상권     2     2  200000  23535634  0.0434
경기       수도권     3     3  300000  13453264  0.0944


배열 인덱싱 - 


feature   지역  2010  2012    2017      2022     증가율
city                                              
서울       특별시     1     1  100000  35325412  0.2324
부산       경상권     2     2  200000  23535634  0.0434
경기       수도권     3     3  300000  13453264  0.0944