In [2]:
import numpy as np
np.__version__

'1.20.3'

In [3]:
def aryInfo(ary) :
    print('type - ' , type(ary))
    print('shape - ' , ary.shape)
    print('dimension - ' , ary.ndim)
    print('dtype - ' , ary.dtype)
    print()
    print('data - \n' , ary)

In [3]:
oneAry = np.array([0,1,2,3,4,5,6,7,8,9])
aryInfo(oneAry)

type -  <class 'numpy.ndarray'>
shape -  (10,)
dimension -  1
dtype -  int64

data - 
 [0 1 2 3 4 5 6 7 8 9]


In [4]:
data = [0,1,2,3,4,5,6,7,8,9]
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
result = []

for d in data :
    result.append(d * 2)

print(result)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [6]:
result2 = [d * 2 for d in data]
print(result2)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [7]:
result3 = oneAry * 2
print(result3)

[ 0  2  4  6  8 10 12 14 16 18]


In [6]:
data01 = [1, 2, 3, 4, 5]
data02 = [10, 20, 30, 40, 50]

print(type(data01) , type(data02))

<class 'list'> <class 'list'>


In [7]:
xAry = np.array(data01)
yAry = np.array(data02)

print(type(xAry) , type(yAry))

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [8]:
print('산술연산 - ')

aryInfo(xAry + yAry)

print()
aryInfo(2 * xAry + yAry)

산술연산 - 
type -  <class 'numpy.ndarray'>
shape -  (5,)
dimension -  1
dtype -  int64

data - 
 [11 22 33 44 55]

type -  <class 'numpy.ndarray'>
shape -  (5,)
dimension -  1
dtype -  int64

data - 
 [12 24 36 48 60]


In [9]:
print('비교 연산 - boolean masking')

print( xAry == 2 )
print()
aryInfo(xAry == 2 )

비교 연산 - boolean masking
[False  True False False False]

type -  <class 'numpy.ndarray'>
shape -  (5,)
dimension -  1
dtype -  bool

data - 
 [False  True False False False]


In [10]:
print('비교 연산 - boolean masking')

print( yAry > 10 )
print()
aryInfo( yAry > 10 )

비교 연산 - boolean masking
[False  True  True  True  True]

type -  <class 'numpy.ndarray'>
shape -  (5,)
dimension -  1
dtype -  bool

data - 
 [False  True  True  True  True]


In [12]:
print('논리 연산 - ')
print( (xAry == 2) | (yAry > 10) )
print()
aryInfo( (xAry == 2) | (yAry > 10) )

논리 연산 - 
[False  True  True  True  True]

type -  <class 'numpy.ndarray'>
shape -  (5,)
dimension -  1
dtype -  bool

data - 
 [False  True  True  True  True]
