In [1]:
import numpy  as np
import pandas as pd

import warnings
warnings.filterwarnings(action='ignore')

from datetime import date, datetime, timedelta
from dateutil.parser import parse

import json
import urllib

# titanic dataset
import seaborn as sns



print('numpy  version - ' , np.__version__)
print('pandas version - ' , pd.__version__)

numpy  version -  1.20.3
pandas version -  1.3.4


In [2]:
def seriesInfo(s) :
    print('series : index + values \n' , s)
    print('index  - ' , s.index  , type(s.index))
    print('values - ' , s.values , type(s.values))


In [3]:
def frmInfo(df) :
    display('data - ' , df )
    print()
    print('shape   - ' , df.shape , df.shape[0] , df.shape[1])
    print('size    - ' , df.size )
    print('ndim    - ' , df.ndim)
    print('index   - ' , df.index    , type(df.index))
    print('columns - ' , df.columns  , type( df.columns ))
    print('values  - \n' , df.values , type(df.values) )

In [4]:
score_data = {
    'kor'  : [80, 90, 70, 30] ,
    'eng'  : [90, 70, 60, 40] ,
    'math' : [90, 60, 90, 70] ,
}

col_idx = ['kor' , 'eng' , 'math']
row_idx = ['Jason' , 'Jaso' , 'Ja' , 'J']

tmp_frm = pd.DataFrame(score_data , columns = col_idx , index = row_idx)
frmInfo(tmp_frm)

'data - '

kor  eng  math
Jason   80   90    90
Jaso    90   70    60
Ja      70   60    90
J       30   40    70


shape   -  (4, 3) 4 3
size    -  12
ndim    -  2
index   -  Index(['Jason', 'Jaso', 'Ja', 'J'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['kor', 'eng', 'math'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[80 90 90]
 [90 70 60]
 [70 60 90]
 [30 40 70]] <class 'numpy.ndarray'>


In [5]:
print( tmp_frm['kor'] , type(tmp_frm['kor']) )

Jason    80
Jaso     90
Ja       70
J        30
Name: kor, dtype: int64 <class 'pandas.core.series.Series'>


In [6]:
print('모든 학생의 영어 점수와 국어점수만 조회한다면? ')
print()
frmInfo( tmp_frm[ ['kor' , 'eng'] ]  )

모든 학생의 영어 점수와 국어점수만 조회한다면? 



'data - '

kor  eng
Jason   80   90
Jaso    90   70
Ja      70   60
J       30   40


shape   -  (4, 2) 4 2
size    -  8
ndim    -  2
index   -  Index(['Jason', 'Jaso', 'Ja', 'J'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['kor', 'eng'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[80 90]
 [90 70]
 [70 60]
 [30 40]] <class 'numpy.ndarray'>


In [7]:
print('모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다면? - ')
print()
tmp_frm['avg'] = np.mean( tmp_frm.T )
tmp_frm

모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다면? - 



kor  eng  math        avg
Jason   80   90    90  86.666667
Jaso    90   70    60  73.333333
Ja      70   60    90  73.333333
J       30   40    70  46.666667

In [8]:
print('Jaso 학생의 영어점수를 90점으로 수정하고 평균 점수도 다시 계산한다면? ')
print()
tmp_frm['eng']['Jaso'] = 90
tmp_frm['avg'] = np.mean( tmp_frm.T )
tmp_frm

Jaso 학생의 영어점수를 90점으로 수정하고 평균 점수도 다시 계산한다면? 



kor  eng  math        avg
Jason   80   90    90  86.666667
Jaso    90   90    60  78.333333
Ja      70   60    90  73.333333
J       30   40    70  46.666667

In [9]:
print( tmp_frm[ :'Ja'] , type(tmp_frm[ :'Ja']) )


       kor  eng  math        avg
Jason   80   90    90  86.666667
Jaso    90   90    60  78.333333
Ja      70   60    90  73.333333 <class 'pandas.core.frame.DataFrame'>


In [10]:
print( tmp_frm.T['Ja'] , type(tmp_frm.T['Ja']) )

kor     70.000000
eng     60.000000
math    90.000000
avg     73.333333
Name: Ja, dtype: float64 <class 'pandas.core.series.Series'>


In [11]:
sample_frm = pd.DataFrame( np.arange(10, 22).reshape(3,4) ,
                           index = ['a', 'b', 'c'] ,
                           columns = ['col01' , 'col02', 'col03' , 'col04'])
sample_frm

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     18     19     20     21

In [12]:
seriesInfo( sample_frm.loc['a'] )


series : index + values 
 col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int64
index  -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values -  [10 11 12 13] <class 'numpy.ndarray'>


In [13]:
print('loc[행 인덱스 값 , 열 인덱스 값]')

sample_frm.loc['a'].values

loc[행 인덱스 값 , 열 인덱스 값]


array([10, 11, 12, 13])

In [14]:
sample_frm.iloc[0]

col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int64

In [15]:
sample_frm.loc[ ['a','c'] ]

col01  col02  col03  col04
a     10     11     12     13
c     18     19     20     21

In [16]:
sample_frm.iloc[ [0 , 2] ]

col01  col02  col03  col04
a     10     11     12     13
c     18     19     20     21

In [17]:
sample_frm.loc[ 'b' : 'c']

col01  col02  col03  col04
b     14     15     16     17
c     18     19     20     21

In [18]:
sample_frm[ 'b' : 'c' ]

col01  col02  col03  col04
b     14     15     16     17
c     18     19     20     21

In [19]:
sample_frm.loc[ ['b' , 'c'] ]

col01  col02  col03  col04
b     14     15     16     17
c     18     19     20     21

In [20]:
sample_frm['col01'] > 15

a    False
b    False
c     True
Name: col01, dtype: bool

In [21]:
sample_frm.loc[ sample_frm['col01'] > 15 ]

col01  col02  col03  col04
c     18     19     20     21

In [22]:
sample_frm.loc[sample_frm['col02'] >10]

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     18     19     20     21

In [23]:
sample_frm.loc['a','col01']
sample_frm.loc['b','col03']
sample_frm.loc['a','col02']

11

In [24]:
sample_frm.loc['a':'b', 'col03']
sample_frm.loc['a':'d', 'col02']

a    11
b    15
c    19
Name: col02, dtype: int64

In [25]:
''' 슬라이싱 & 인덱싱이 중요한 이유는 데이터는 우리가 원하는대로 존재하지 않는다. 내가 원하는 데이터로 변환을 하고
 원하는 데이터 셋을 만들려면 판다스는 기본적으로 해야하는것이고 넘파이도 당연히 알야한다. '''

' 슬라이싱 & 인덱싱이 중요한 이유는 데이터는 우리가 원하는대로 존재하지 않는다. 내가 원하는 데이터로 변환을 하고\n 원하는 데이터 셋을 만들려면 판다스는 기본적으로 해야하는것이고 넘파이도 당연히 알야한다. '

In [26]:
sample_frm.loc['a', :]

col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int64

In [27]:
sample_frm.loc['b',:]

col01    14
col02    15
col03    16
col04    17
Name: b, dtype: int64

In [28]:
sample_frm.loc['c', :]

col01    18
col02    19
col03    20
col04    21
Name: c, dtype: int64

In [29]:
print('이런식으로 명령어를 입력시 구간을 가지고 오지 않고 col01 and col03의 a값만 가지고 오게된다.')
sample_frm.loc['a', ['col01', 'col03']]

이런식으로 명령어를 입력시 구간을 가지고 오지 않고 col01 and col03의 a값만 가지고 오게된다.


col01    10
col03    12
Name: a, dtype: int64

In [30]:
print('loc와 iloc 의 차이를 쉽게 알 수 있다.')
sample_frm.iloc[: , -2:]

loc와 iloc 의 차이를 쉽게 알 수 있다.


col03  col04
a     12     13
b     16     17
c     20     21

In [31]:
sample_frm.iloc[-1] = sample_frm.iloc[-1]*2
sample_frm.iloc[-1]

sample_frm.iloc[1] = sample_frm.iloc[1]*2
sample_frm.iloc[1]

col01    28
col02    30
col03    32
col04    34
Name: b, dtype: int64

In [32]:
sample_frm.loc['d'] = 0
sample_frm

col01  col02  col03  col04
a     10     11     12     13
b     28     30     32     34
c     36     38     40     42
d      0      0      0      0

In [33]:
sample_frm.loc['e'] = sample_frm.loc['d']
sample_frm


col01  col02  col03  col04
a     10     11     12     13
b     28     30     32     34
c     36     38     40     42
d      0      0      0      0
e      0      0      0      0

In [34]:
print('열 추가도 위에 방식과 크게 다르지 않다.')
sample_frm['col05'] = sample_frm['col04']
sample_frm

열 추가도 위에 방식과 크게 다르지 않다.


col01  col02  col03  col04  col05
a     10     11     12     13     13
b     28     30     32     34     34
c     36     38     40     42     42
d      0      0      0      0      0
e      0      0      0      0      0

In [35]:
sample_frm.iloc[1,1]
sample_frm.iloc[1, -1]

34

In [36]:
tmp_series = pd.Series(np.arange(10))
tmp_series[5] = np.NAN

In [37]:
tmp_series.count()

9

In [38]:
cnt_frm = pd.DataFrame(np.random.randint(5, size=(4,4)),
                       columns=['col01','col02','col03','col04'])
cnt_frm

col01  col02  col03  col04
0      1      4      3      0
1      1      1      1      4
2      1      0      3      4
3      2      0      1      3

In [39]:
cnt_frmm = pd.DataFrame(np.random.randint(5,size=(5,5)),
                        columns=['col1','col2', 'col3', 'col4','col5'])
cnt_frmm

col1  col2  col3  col4  col5
0     3     0     3     2     3
1     0     3     1     4     3
2     0     4     2     2     2
3     3     2     2     1     1
4     2     2     1     3     1

In [40]:
cnt_frm.iloc[1,-1] = np.NaN
cnt_frm.iloc[3,1] = np.NaN
cnt_frm.iloc[2,2] = np.NaN

In [41]:
cnt_frm

col01  col02  col03  col04
0      1    4.0    3.0    0.0
1      1    1.0    1.0    NaN
2      1    0.0    NaN    4.0
3      2    NaN    1.0    3.0

In [42]:
cnt_frm.count()

col01    4
col02    3
col03    3
col04    3
dtype: int64

In [43]:
datasets = sns.load_dataset('titanic')
print('type - ' , type(datasets))

type -  <class 'pandas.core.frame.DataFrame'>


In [44]:
datasets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [45]:
datasets.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [46]:
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [47]:
datasets.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [48]:
check = datasets.count()

In [49]:
print(type(check))

<class 'pandas.core.series.Series'>


In [50]:
print('유의사항 - 명령어를 사용할 때 복수형인지 단수형인지 생각하고 입력하기 ')

datasets['class'].value_counts().values

유의사항 - 명령어를 사용할 때 복수형인지 단수형인지 생각하고 입력하기 


array([491, 216, 184])

In [51]:
datasets['New_col'] = 0

In [52]:
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  New_col  
0    man        True  NaN  Southampton    no  False        0  
1  woman       False    C    Cherbourg   yes  False        0  
2  woman       False  NaN  Southampton   yes   True        0  
3  woman       False    C  Southampton   yes  False        0  
4    man        True  NaN  Southampton    no   True        0

In [53]:
del datasets['New_col']
datasets.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [54]:
print('age_by_10 컬럼을 추가하고자 한다 - ')
print('age 컬럼의 값에 10살을 더한 값으로 일괄 적용한다면? - ')
print()
datasets['age_by_10'] = datasets['age'] + 10
datasets.head()

age_by_10 컬럼을 추가하고자 한다 - 
age 컬럼의 값에 10살을 더한 값으로 일괄 적용한다면? - 



survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  
0    man        True  NaN  Southampton    no  False       32.0  
1  woman       False    C    Cherbourg   yes  False       48.0  
2  woman       False  NaN  Southampton   yes   True       36.0  
3  woman       False    C  Southampton   yes  False       45.0  
4    man        True  NaN  Southampton    no   True       45.0

In [55]:
datasets['parch'].value_counts()

0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: parch, dtype: int64

In [56]:
print('parch 와 sibsp의 값과 1을 더한 family_no 컬럼 생성한다면? - ')
print()

datasets['family_no'] = datasets['parch'] + datasets['sibsp'] + 1

datasets.head()

parch 와 sibsp의 값과 1을 더한 family_no 컬럼 생성한다면? - 



survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  age_by_10  family_no  
0    man        True  NaN  Southampton    no  False       32.0          2  
1  woman       False    C    Cherbourg   yes  False       48.0          2  
2  woman       False  NaN  Southampton   yes   True       36.0          1  
3  woman       False    C  Southampton   yes  False       45.0          2  
4    man        True  NaN  Southampton    no   True       45.0          1

In [57]:
print('새롭게 만든 2개의 컬럼을 삭제한다면? drop() 이용 - ')
print()

datasets.drop(['age_by_10' , 'family_no'] , axis = 1 , inplace = True)
datasets

새롭게 만든 2개의 컬럼을 삭제한다면? drop() 이용 - 



survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [58]:
type( datasets.index.values )
datasets.index.values[ : 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
type( datasets.columns.values )
print(datasets.columns.values[:10])

['survived' 'pclass' 'sex' 'age' 'sibsp' 'parch' 'fare' 'embarked' 'class'
 'who']


In [64]:
fare_series = datasets['fare']
print('type -', type(fare_series))
print()
print('data - ', fare_series.values, type(fare_series.values))

type - <class 'pandas.core.series.Series'>

data -  [  7.25    71.2833   7.925   53.1      8.05     8.4583  51.8625  21.075
  11.1333  30.0708  16.7     26.55     8.05    31.275    7.8542  16.
  29.125   13.      18.       7.225   26.      13.       8.0292  35.5
  21.075   31.3875   7.225  263.       7.8792   7.8958  27.7208 146.5208
   7.75    10.5     82.1708  52.       7.2292   8.05    18.      11.2417
   9.475   21.       7.8958  41.5792   7.8792   8.05    15.5      7.75
  21.6792  17.8     39.6875   7.8     76.7292  26.      61.9792  35.5
  10.5      7.2292  27.75    46.9      7.2292  80.      83.475   27.9
  27.7208  15.2458  10.5      8.1583   7.925    8.6625  10.5     46.9
  73.5     14.4542  56.4958   7.65     7.8958   8.05    29.      12.475
   9.       9.5      7.7875  47.1     10.5     15.85    34.375    8.05
 263.       8.05     8.05     7.8542  61.175   20.575    7.25     8.05
  34.6542  63.3583  23.      26.       7.8958   7.8958  77.2875   8.6542
   7.925    7.8958   7.

In [69]:
print('두가지 방법으로 연산이 가능하다.')
print('max -', np.max(fare_series))
print('min -', np.min(fare_series), fare_series.min())
print('sum -', np.sum(fare_series), fare_series.sum())

두가지 방법으로 연산이 가능하다.
max - 512.3292
min - 0.0 0.0
sum - 28693.9493 28693.9493


In [70]:
datasets.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [71]:
print('인덱스를 재정의 하는 방법')
print('reset_index() : 새로운 인덱스 할, 기존의 인덱스를 열로 추가할 수 있다.')
print('set_index()')

인덱스를 재정의 하는 방법
reset_index() : 새로운 인덱스 할, 기존의 인덱스를 열로 추가할 수 있다.
set_index()


In [73]:
titanic_dataset = pd.read_csv('/Users/choijaewoo/pandas_data/titanic_train.csv')
titanic_dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [74]:
titanic_set_index = titanic_dataset.set_index('PassengerId')
titanic_dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [75]:
titanic_reset_index = titanic_dataset.reset_index(inplace = False)
titanic_reset_index

index  PassengerId  Survived  Pclass  \
0        0            1         0       3   
1        1            2         1       1   
2        2            3         1       3   
3        3            4         1       1   
4        4            5         0       3   
..     ...          ...       ...     ...   
886    886          887         0       2   
887    887          888         1       1   
888    888          889         0       3   
889    889          890         1       1   
890    890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 13 columns]

In [76]:
titanic_dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [83]:
print('Pclass 가 3 등급인 데이터만 확인 - ')
boolean_idx = titanic_dataset['Pclass'] == 3
boolean_idx.value_counts()
titanic_dataset[boolean_idx].iloc[ : , [4, 5]]
titanic_dataset[boolean_idx][['Sex','Age']]


Pclass 가 3 등급인 데이터만 확인 - 


Sex   Age
0      male  22.0
2    female  26.0
4      male  35.0
5      male   NaN
7      male   2.0
..      ...   ...
882  female  22.0
884    male  25.0
885  female  39.0
888  female   NaN
890    male  32.0

[491 rows x 2 columns]

In [85]:
print('나이가 60 이상인 정보만 출력한다면 - ')
print('Pclass , Survived, Name - loc[] ')
print()
titanic_subset = titanic_dataset.loc[titanic_dataset['Age'] >= 60 , ['Pclass','Survived', 'Name']]
titanic_subset

나이가 60 이상인 정보만 출력한다면 - 
Pclass , Survived, Name - loc[] 



Pclass  Survived                                              Name
33        2         0                             Wheadon, Mr. Edward H
54        1         0                    Ostby, Mr. Engelhart Cornelius
96        1         0                         Goldschmidt, Mr. George B
116       3         0                              Connors, Mr. Patrick
170       1         0                         Van der hoef, Mr. Wyckoff
252       1         0                         Stead, Mr. William Thomas
275       1         1                 Andrews, Miss. Kornelia Theodosia
280       3         0                                  Duane, Mr. Frank
326       3         0                         Nysveen, Mr. Johan Hansen
366       1         1  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)
438       1         0                                 Fortune, Mr. Mark
456       1         0                         Millet, Mr. Francis Davis
483       3         1                            Turkula, Mrs. (Hedwig)
493       1         0                           Artagaveytia, Mr. Ramon
545       1         0                      Nicholson, Mr. Arthur Ernest
555       1         0                                Wright, Mr. George
570       2         1                                Harris, Mr. George
587       1         1                  Frolicher-Stehli, Mr. Maxmillian
625       1         0                             Sutton, Mr. Frederick
630       1         1              Barkworth, Mr. Algernon Henry Wilson
672       2         0                       Mitchell, Mr. Henry Michael
684       2         0                 Brown, Mr. Thomas William Solomon
694       1         0                                   Weir, Col. John
745       1         0                      Crosby, Capt. Edward Gifford
829       1         1         Stone, Mrs. George Nelson (Martha Evelyn)
851       3         0                               Svensson, Mr. Johan