In [1]:
import numpy  as np
import pandas as pd

import warnings
warnings.filterwarnings(action='ignore')

from datetime import date, datetime, timedelta
from dateutil.parser import parse

import json
import urllib

# titanic dataset
import seaborn as sns



print('numpy  version - ' , np.__version__)
print('pandas version - ' , pd.__version__)

numpy  version -  1.20.3
pandas version -  1.3.4


In [2]:
def seriesInfo(s) :
    print('series : index + values \n' , s)
    print('index  - ' , s.index  , type(s.index))
    print('values - ' , s.values , type(s.values))


In [3]:
def frmInfo(df) :
    display('data - ' , df )
    print()
    print('shape   - ' , df.shape , df.shape[0] , df.shape[1])
    print('size    - ' , df.size )
    print('ndim    - ' , df.ndim)
    print('index   - ' , df.index    , type(df.index))
    print('columns - ' , df.columns  , type( df.columns ))
    print('values  - \n' , df.values , type(df.values) )

In [4]:
score_data = {
    'kor'  : [80, 90, 70, 30] ,
    'eng'  : [90, 70, 60, 40] ,
    'math' : [90, 60, 90, 70] ,
}

col_idx = ['kor' , 'eng' , 'math']
row_idx = ['Jason' , 'Jaso' , 'Ja' , 'J']

tmp_frm = pd.DataFrame(score_data , columns = col_idx , index = row_idx)
frmInfo(tmp_frm)

'data - '

kor  eng  math
Jason   80   90    90
Jaso    90   70    60
Ja      70   60    90
J       30   40    70


shape   -  (4, 3) 4 3
size    -  12
ndim    -  2
index   -  Index(['Jason', 'Jaso', 'Ja', 'J'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['kor', 'eng', 'math'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[80 90 90]
 [90 70 60]
 [70 60 90]
 [30 40 70]] <class 'numpy.ndarray'>


In [5]:
print( tmp_frm['kor'] , type(tmp_frm['kor']) )

Jason    80
Jaso     90
Ja       70
J        30
Name: kor, dtype: int64 <class 'pandas.core.series.Series'>


In [6]:
print('모든 학생의 영어 점수와 국어점수만 조회한다면? ')
print()
frmInfo( tmp_frm[ ['kor' , 'eng'] ]  )

모든 학생의 영어 점수와 국어점수만 조회한다면? 



'data - '

kor  eng
Jason   80   90
Jaso    90   70
Ja      70   60
J       30   40


shape   -  (4, 2) 4 2
size    -  8
ndim    -  2
index   -  Index(['Jason', 'Jaso', 'Ja', 'J'], dtype='object') <class 'pandas.core.indexes.base.Index'>
columns -  Index(['kor', 'eng'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[80 90]
 [90 70]
 [70 60]
 [30 40]] <class 'numpy.ndarray'>


In [7]:
print('모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다면? - ')
print()
tmp_frm['avg'] = np.mean( tmp_frm.T )
tmp_frm

모든 학생의 각 과목 평균 점수를 새로운 열로 추가한다면? - 



kor  eng  math        avg
Jason   80   90    90  86.666667
Jaso    90   70    60  73.333333
Ja      70   60    90  73.333333
J       30   40    70  46.666667

In [8]:
print('Jaso 학생의 영어점수를 90점으로 수정하고 평균 점수도 다시 계산한다면? ')
print()
tmp_frm['eng']['Jaso'] = 90
tmp_frm['avg'] = np.mean( tmp_frm.T )
tmp_frm

Jaso 학생의 영어점수를 90점으로 수정하고 평균 점수도 다시 계산한다면? 



kor  eng  math        avg
Jason   80   90    90  86.666667
Jaso    90   90    60  78.333333
Ja      70   60    90  73.333333
J       30   40    70  46.666667

In [9]:
print( tmp_frm[ :'Ja'] , type(tmp_frm[ :'Ja']) )


       kor  eng  math        avg
Jason   80   90    90  86.666667
Jaso    90   90    60  78.333333
Ja      70   60    90  73.333333 <class 'pandas.core.frame.DataFrame'>


In [10]:
print( tmp_frm.T['Ja'] , type(tmp_frm.T['Ja']) )

kor     70.000000
eng     60.000000
math    90.000000
avg     73.333333
Name: Ja, dtype: float64 <class 'pandas.core.series.Series'>


In [11]:
sample_frm = pd.DataFrame( np.arange(10, 22).reshape(3,4) ,
                           index = ['a', 'b', 'c'] ,
                           columns = ['col01' , 'col02', 'col03' , 'col04'])
sample_frm

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     18     19     20     21

In [12]:
seriesInfo( sample_frm.loc['a'] )


series : index + values 
 col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int64
index  -  Index(['col01', 'col02', 'col03', 'col04'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values -  [10 11 12 13] <class 'numpy.ndarray'>


In [13]:
print('loc[행 인덱스 값 , 열 인덱스 값]')

sample_frm.loc['a'].values

loc[행 인덱스 값 , 열 인덱스 값]


array([10, 11, 12, 13])

In [14]:
sample_frm.iloc[0]

col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int64

In [15]:
sample_frm.loc[ ['a','c'] ]

col01  col02  col03  col04
a     10     11     12     13
c     18     19     20     21

In [16]:
sample_frm.iloc[ [0 , 2] ]

col01  col02  col03  col04
a     10     11     12     13
c     18     19     20     21

In [17]:
sample_frm.loc[ 'b' : 'c']

col01  col02  col03  col04
b     14     15     16     17
c     18     19     20     21

In [18]:
sample_frm[ 'b' : 'c' ]

col01  col02  col03  col04
b     14     15     16     17
c     18     19     20     21

In [19]:
sample_frm.loc[ ['b' , 'c'] ]

col01  col02  col03  col04
b     14     15     16     17
c     18     19     20     21

In [20]:
sample_frm['col01'] > 15

a    False
b    False
c     True
Name: col01, dtype: bool

In [21]:
sample_frm.loc[ sample_frm['col01'] > 15 ]

col01  col02  col03  col04
c     18     19     20     21

In [24]:
sample_frm.loc[sample_frm['col02'] >10]

col01  col02  col03  col04
a     10     11     12     13
b     14     15     16     17
c     18     19     20     21

In [28]:
sample_frm.loc['a','col01']
sample_frm.loc['b','col03']
sample_frm.loc['a','col02']

11

In [31]:
sample_frm.loc['a':'b', 'col03']
sample_frm.loc['a':'d', 'col02']

a    11
b    15
c    19
Name: col02, dtype: int64

In [36]:
''' 슬라이싱 & 인덱싱이 중요한 이유는 데이터는 우리가 원하는대로 존재하지 않는다. 내가 원하는 데이터로 변환을 하고
 원하는 데이터 셋을 만들려면 판다스는 기본적으로 해야하는것이고 넘파이도 당연히 알야한다. '''

' 슬라이싱 & 인덱싱이 중요한 이유는 데이터는 우리가 원하는대로 존재하지 않는다. 내가 원하는 데이터로 변환을 하고\n 원하는 데이터 셋을 만들려면 판다스는 기본적으로 해야하는것이고 넘파이도 당연히 알야한다. '

In [33]:
sample_frm.loc['a', :]

col01    10
col02    11
col03    12
col04    13
Name: a, dtype: int64

In [34]:
sample_frm.loc['b',:]

col01    14
col02    15
col03    16
col04    17
Name: b, dtype: int64

In [35]:
sample_frm.loc['c', :]

col01    18
col02    19
col03    20
col04    21
Name: c, dtype: int64

In [40]:
print('이런식으로 명령어를 입력시 구간을 가지고 오지 않고 col01 and col03의 a값만 가지고 오게된다.')
sample_frm.loc['a', ['col01', 'col03']]

이런식으로 명령어를 입력시 구간을 가지고 오지 않고 col01 and col03의 a값만 가지고 오게된다.


col01    10
col03    12
Name: a, dtype: int64

In [43]:
print('loc와 iloc 의 차이를 쉽게 알 수 있다.')
sample_frm.iloc[: , -2:]

loc와 iloc 의 차이를 쉽게 알 수 있다.


col03  col04
a     12     13
b     16     17
c     20     21