In [1]:
import numpy  as np
import pandas as pd

import warnings
warnings.filterwarnings(action='ignore')

from datetime import date, datetime, timedelta
from dateutil.parser import parse

import json
import urllib

# titanic dataset
import seaborn as sns

# 비정형 데이터 처리를 위한 라이브러리
from bs4 import BeautifulSoup
import requests
import re



print('numpy  version - ' , np.__version__)
print('pandas version - ' , pd.__version__)

numpy  version -  1.20.3
pandas version -  1.3.4


In [2]:
def seriesInfo(s) :
    print('series : index + values \n' , s)
    print('index  - ' , s.index  , type(s.index))
    print('values - ' , s.values , type(s.values))

def frmInfo(df) :
    display('data - ' , df )
    print()
    print('shape   - ' , df.shape , df.shape[0] , df.shape[1])
    print('size    - ' , df.size )
    print('ndim    - ' , df.ndim)
    print('index   - ' , df.index    , type(df.index))
    print('columns - ' , df.columns  , type( df.columns ))
    print('values  - \n' , df.values , type(df.values) )

In [3]:
tmp_frm = pd.read_csv('/Users/choijaewoo/pandas_data/read_csv_sample.csv')
frmInfo(tmp_frm)

'data - '

c0  c1  c2  c3
0   0   1   4   7
1   1   2   5   8
2   2   3   6   9


shape   -  (3, 4) 3 4
size    -  12
ndim    -  2
index   -  RangeIndex(start=0, stop=3, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns -  Index(['c0', 'c1', 'c2', 'c3'], dtype='object') <class 'pandas.core.indexes.base.Index'>
values  - 
 [[0 1 4 7]
 [1 2 5 8]
 [2 3 6 9]] <class 'numpy.ndarray'>


In [4]:
tmp_frm = pd.read_csv('/Users/choijaewoo/pandas_data/read_csv_sample.csv' , header = None)
frmInfo(tmp_frm)

'data - '

0   1   2   3
0  c0  c1  c2  c3
1   0   1   4   7
2   1   2   5   8
3   2   3   6   9


shape   -  (4, 4) 4 4
size    -  16
ndim    -  2
index   -  RangeIndex(start=0, stop=4, step=1) <class 'pandas.core.indexes.range.RangeIndex'>
columns -  Int64Index([0, 1, 2, 3], dtype='int64') <class 'pandas.core.indexes.numeric.Int64Index'>
values  - 
 [['c0' 'c1' 'c2' 'c3']
 ['0' '1' '4' '7']
 ['1' '2' '5' '8']
 ['2' '3' '6' '9']] <class 'numpy.ndarray'>
