In [1]:
'''
- machine learning 은 데이터를 기반으로 패턴을 학습하고 결과를 추론하는 알고리즘 기법
- 지도 학습(supervised learning), 비지도 학습(unsupervised leanring), 강화학습(reinforcement learning)으로 3가지로 나뉘게 된다
- 지도 학습: 분류(Classification), 회귀(regression)
- 비지도 학습: 군집화(클러스터링), 차원축소(PCA)

머신러닝에서 기본으로 알아야 하는 용어

feature : 머신러닝에서 데이터를 피쳐로 말한다. *데이터의 일반속성
결정값을 의미 하는 용어: target, label, class, 결정값이라고 말하면 여기서 결정값은 정답데이터를 의미한다.

'''

'\n- machine learning 은 데이터를 기반으로 패턴을 학습하고 결과를 추론하는 알고리즘 기법\n- 지도 학습(supervised learning), 비지도 학습(unsupervised leanring), 강화학습(reinforcement learning)으로 3가지로 나뉘게 된다\n- 지도 학습: 분류(Classification), 회귀(regression)\n- 비지도 학습: 군집화(클러스터링), 차원축소(PCA)\n\n머신러닝에서 기본으로 알아야 하는 용어\n\nfeature : 머신러닝에서 데이터를 피쳐로 말한다. *데이터의 일반속성\n결정값을 의미 하는 용어: target, label, class, 결정값이라고 말하면 여기서 결정값은 정답데이터를 의미한다.\n\n'

In [16]:
import numpy  as np
import pandas as pd

import warnings
warnings.filterwarnings(action='ignore')

from datetime import date, datetime, timedelta
from dateutil.parser import parse

import matplotlib.pyplot as plt
%matplotlib inline

import json
import urllib

# titanic dataset
import seaborn as sns

# 비정형 데이터 처리를 위한 라이브러리
from bs4 import BeautifulSoup
import requests
import re

from bs4 import BeautifulSoup
from urllib.request import urlopen, urlretrieve
from urllib.error import HTTPError
from urllib.error import URLError

import requests
import re

from time import sleep, time
from random import randint
from IPython.core.display import clear_output

from selenium import webdriver
# print('numpy  version - ' , np.__version__)
# print('pandas version - ' , pd.__version__)

# ml
import sklearn
from sklearn.datasets import load_iris,load_breast_cancer

from sklearn.model_selection import train_test_split,KFold, StratifiedKFold, cross_val_score, cross_validate, GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
sklearn.__version__



'0.24.2'

In [6]:
iris = load_iris()
print('type -', type(iris))
print('key - ', iris.keys())

type - <class 'sklearn.utils.Bunch'>
key -  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [7]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
iris.target


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [10]:
print('feature, target를 이용해서 데이터프레임을 만들어 보자')

iris_frm = pd.DataFrame(data = iris.data,
                       columns = iris.feature_names)

iris_frm['target'] = iris.target
iris_frm

feature, target를 이용해서 데이터프레임을 만들어 보자


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [11]:
print('step01 - 데이터세트 분리')

X_train, X_test, y_train, y_test = train_test_split(iris.data,
                iris.target,
                test_size = 0.2,
                shuffle = True,
                random_state = 200) # test_size가 나눈다는 의미 x는 데이터(피쳐) y는 정답 (타켓)
print('train data - ', X_train)
print('train target - ', y_train)
print()
print('train data - ', X_test)
print('train target - ', y_test)


step01 - 데이터세트 분리
train data -  [[5.1 3.4 1.5 0.2]
 [5.7 2.8 4.1 1.3]
 [5.8 2.6 4.  1.2]
 [5.  3.6 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.3 3.7 1.5 0.2]
 [5.4 3.7 1.5 0.2]
 [4.9 3.1 1.5 0.1]
 [6.1 3.  4.9 1.8]
 [6.7 3.1 4.7 1.5]
 [5.6 3.  4.1 1.3]
 [4.8 3.  1.4 0.1]
 [5.1 3.7 1.5 0.4]
 [5.6 3.  4.5 1.5]
 [5.7 2.5 5.  2. ]
 [6.  2.2 5.  1.5]
 [7.7 3.  6.1 2.3]
 [5.  3.  1.6 0.2]
 [6.8 3.2 5.9 2.3]
 [6.3 2.3 4.4 1.3]
 [7.7 2.6 6.9 2.3]
 [5.8 2.7 4.1 1. ]
 [6.4 2.9 4.3 1.3]
 [5.6 2.7 4.2 1.3]
 [5.6 2.8 4.9 2. ]
 [5.5 3.5 1.3 0.2]
 [6.  2.7 5.1 1.6]
 [5.6 2.5 3.9 1.1]
 [6.1 2.8 4.7 1.2]
 [6.3 2.8 5.1 1.5]
 [4.4 2.9 1.4 0.2]
 [5.  3.3 1.4 0.2]
 [6.8 3.  5.5 2.1]
 [5.1 3.5 1.4 0.3]
 [5.7 4.4 1.5 0.4]
 [6.5 3.  5.8 2.2]
 [6.1 3.  4.6 1.4]
 [5.1 3.8 1.6 0.2]
 [5.  3.5 1.6 0.6]
 [5.8 2.7 5.1 1.9]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [7.2 3.2 6.  1.8]
 [6.3 2.9 5.6 1.8]
 [6.1 2.8 4.  1.3]
 [6.7 3.1 4.4 1.4]
 [5.9 3.  5.1 1.8]
 [5.  3.5 1.3 0.3]
 [5.4 3.9 1.7 0.4]
 [7.9 3.8 6.4 2. ]
 [4.9 2.4 3.3 1. ]

In [12]:
print('estimater 생성 및 학습')
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)

estimater 생성 및 학습


DecisionTreeClassifier()

In [13]:
print('predict 함수에 테스트 데이터를 넣어서 분류예측 값을 반환 - ')

y_pred = dt_model.predict(X_test)
print('answer - ', y_test)
print('pred', y_pred)

predict 함수에 테스트 데이터를 넣어서 분류예측 값을 반환 - 
answer -  [1 2 0 0 1 2 1 1 1 2 2 0 0 0 2 0 1 0 1 2 0 1 2 0 0 0 1 2 2 1]
pred [1 2 0 0 1 2 1 1 1 2 2 0 0 0 2 0 1 0 1 2 0 1 2 0 0 0 1 2 2 1]


In [14]:
print('성능평가 - ')
print('예측 정확도 - ', accuracy_score(y_test, y_pred))

성능평가 - 
예측 정확도 -  1.0


In [15]:
print('데이터프레임을 이용한 학습데이터와 테스트 데이터분리후 모델생성 및 예측, 평가를 진행해 본다면 - ')
print('case02 - ')

iris_frm

데이터프레임을 이용한 학습데이터와 테스트 데이터분리후 모델생성 및 예측, 평가를 진행해 본다면 - 
case02 - 


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [17]:
params = {
    'criterion' : ['gini' , 'entropy'] ,
    'splitter'  : ['best' , 'random']  ,
    'max_depth' : [1 , 2 , 3 ] ,
    'min_samples_split' : [2 , 3]
}

iris = load_iris()

X_train , X_test , y_train , y_test = train_test_split(iris.data   ,
                                                       iris.target ,
                                                       test_size    = 0.25 ,
                                                       shuffle      = True ,
                                                       random_state = 200 )


dt_model = DecisionTreeClassifier(random_state = 100)

# refit -> 가장 좋은 파라미터 설정으로 재학습 시킴
grid_tree_model = GridSearchCV(dt_model , param_grid = params , cv = 3 , refit = True)
grid_tree_model.fit(X_train , y_train)
grid_tree_model.cv_results_

{'mean_fit_time': array([0.00546503, 0.00275461, 0.00410867, 0.003244  , 0.00558901,
        0.00213321, 0.00197299, 0.0025866 , 0.00141207, 0.0011495 ,
        0.00227443, 0.00146468, 0.00097434, 0.00154114, 0.00082493,
        0.0011723 , 0.00101423, 0.00300662, 0.00424735, 0.00389345,
        0.0009199 , 0.00113765, 0.00137711, 0.00096488]),
 'std_fit_time': array([3.84121974e-03, 7.93432442e-04, 1.79031507e-03, 7.71751435e-04,
        1.46780215e-03, 6.40759925e-04, 4.16234382e-04, 1.58153215e-03,
        3.50608245e-04, 4.82981880e-05, 1.01724999e-03, 6.29226827e-04,
        1.09019848e-05, 7.68559760e-04, 3.65939512e-05, 2.64620350e-04,
        2.71070566e-04, 7.16995464e-04, 1.40652093e-03, 1.26735047e-03,
        3.41032107e-05, 4.32955375e-04, 3.59379347e-04, 1.58984617e-04]),
 'mean_score_time': array([0.00237505, 0.00123191, 0.00066145, 0.00202529, 0.00159001,
        0.00115244, 0.00067933, 0.00074244, 0.00078797, 0.00050481,
        0.00062172, 0.00074601, 0.00051037, 0.00

In [18]:
print('최적 파라미터 - ' , grid_tree_model.best_params_ )
print('최고 점수     - ' , grid_tree_model.best_score_ )

최적 파라미터 -  {'criterion': 'gini', 'max_depth': 3, 'min_samples_split': 2, 'splitter': 'best'}
최고 점수     -  0.9464201043148411
